name: Build

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, Linux, X64, dev]
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo workflow is working.
