name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.elasticemail.com
          server_port: 2525
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build and Deploy Successful (PR #${{ env.PR_NUMBER }} from ${{ env.SOURCE_BRANCH }})  # Updated subject with placeholders
          body: |
            The job '${{ github.job }}' in workflow '${{ github.workflow }}' of '${{ github.repository }}' succeeded.
            Pull Request Number: ${{ env.PR_NUMBER }}
          env: |
              PR_NUMBER: ${{ steps.extract_pr_info.outputs.pr_number }}
              SOURCE_BRANCH: ${{ steps.extract_pr_info.outputs.branch_name }}
          to: devops@mobikasa.com
          from: githubactions@mobikasa.net
