name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world! && exit 1
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
        # mail server settings
          server_address: smtp.elasticemail.com
          server_port: 2525
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: 'Build Failure Notification'
          # email body as text
          body: 'Your build has failed. Reverting it back.'
          # comma-separated string, send email to
          to: server@mobikasa.com
          # sender email address
          from: 'test@mobikasa.net'
